src/hooks/useUniswapXSwapCallback.ts
src/hooks/useUniversalRouter.ts

I accidently removed some necessary logic a couple of merge requests ago, getting them back with this MR

reverted swap logic

---

src/theme/colors.ts
src/theme/index.tsx

Update Layout Background to Match New Design

---

src/components/Button/index.tsx
src/components/Web3Status/index.tsx
src/components/swap/SwapHeader.tsx
src/pages/App.tsx
src/theme/components/text.tsx
src/theme/index.tsx

Default font DM Sans; Avenir for headings and btns

---

src/pages/Pool/PositionPage.tsx

Change btn styles

---

src/components/FeeSelector/index.tsx

Hide hardcoded percents

---

src/components/Card/index.tsx
src/pages/AddLiquidity/index.tsx

Fix warnings

---

src/pages/AddLiquidity/index.tsx

Fix prices calc for out-of-range pos

---

src/pages/Swap/index.tsx

Fix calculations for usdPriceDifference

---

src/pages/Pool/index.tsx
src/pages/Rewards/index.tsx

case-insensitive search

---

src/components/Web3Status/index.tsx

Static network status

---

src/state/swap/hooks.tsx

change address validation to starknet for url parameters

---

src/pages/Vault/index.tsx
src/pages/Vaults/index.tsx
src/state/vaults/hooks.tsx

1. my deposit is not showing the correct value on vault landing page, in details page it works fine
2. On the landing page, My Vaults toggle functions in the opposite way.
3. Links to View Contract and View Details are not handled correctly in details page.
4. Learn more link is incorrectly handled on landing page

p3 fixes handled

---

src/pages/Pool/index.tsx
src/pages/Rewards/index.tsx

fix rewards search

---

src/hooks/useV3PositionFees.ts

switch braavos to new cairo calldada

---

src/hooks/starknet-react.ts
src/pages/AddLiquidity/index.tsx
src/state/mint/v3/hooks.tsx

Correct balance checking while adding liq

---

src/pages/Pool/PositionPage.tsx

Position usd values

---

src/components/NavBar/index.tsx
src/components/NavigationTabs/index.tsx
src/components/Pools/index.tsx
src/components/PositionListItem/index.tsx
src/pages/Pool/PositionPage.tsx
src/pages/Pool/index.tsx
src/pages/RouteDefinitions.tsx

Improve navigation

---

src/pages/Rewards/index.tsx

next claim date
remove  the note
40M -> 90M STRK

update data on the rewards page

---

src/pages/Swap/index.tsx
src/state/swap/hooks.tsx

don't display quote for insufficient balance

---

src/pages/Rewards/index.tsx

fix claim btn layout

---

package.json
src/components/AccountDrawer/AuthenticatedHeader.tsx
src/components/Web3Status/index.tsx
yarn.lock

feat: adding pfp

---

src/components/PositionListItem/index.tsx
src/components/PositionPreview/index.tsx

Added proper number type to price to preserve precision

---

package.json
src/components/AccountDrawer/AuthenticatedHeader.tsx
src/components/Web3Status/index.tsx
yarn.lock

Reverts jediswaplabs/jediswap-v2-interface#195
causing infinite requests on frontend due to unknown reason, need to debug

Revert "feat: adding pfp"

---

src/components/Pools/index.tsx

fix rewards filter

---

src/components/vault/styled.tsx

fix vault depo layout

---

src/components/Pools/index.tsx

get token symbol from tokenlist

---

src/components/Pools/index.tsx
src/pages/Pool/index.tsx

searching for top pools
